package org.ertebat.pdb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.ertebat.pdb.FriendEntity;
import org.ertebat.pdb.RoomsMemberEntity;
import org.ertebat.pdb.MessageEntity;
import org.ertebat.pdb.ProfileEntity;
import org.ertebat.pdb.RoomEntity;
import org.ertebat.pdb.MemberEntity;

import org.ertebat.pdb.FriendEntityDao;
import org.ertebat.pdb.RoomsMemberEntityDao;
import org.ertebat.pdb.MessageEntityDao;
import org.ertebat.pdb.ProfileEntityDao;
import org.ertebat.pdb.RoomEntityDao;
import org.ertebat.pdb.MemberEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendEntityDaoConfig;
    private final DaoConfig roomsMemberEntityDaoConfig;
    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig profileEntityDaoConfig;
    private final DaoConfig roomEntityDaoConfig;
    private final DaoConfig memberEntityDaoConfig;

    private final FriendEntityDao friendEntityDao;
    private final RoomsMemberEntityDao roomsMemberEntityDao;
    private final MessageEntityDao messageEntityDao;
    private final ProfileEntityDao profileEntityDao;
    private final RoomEntityDao roomEntityDao;
    private final MemberEntityDao memberEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendEntityDaoConfig = daoConfigMap.get(FriendEntityDao.class).clone();
        friendEntityDaoConfig.initIdentityScope(type);

        roomsMemberEntityDaoConfig = daoConfigMap.get(RoomsMemberEntityDao.class).clone();
        roomsMemberEntityDaoConfig.initIdentityScope(type);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        profileEntityDaoConfig = daoConfigMap.get(ProfileEntityDao.class).clone();
        profileEntityDaoConfig.initIdentityScope(type);

        roomEntityDaoConfig = daoConfigMap.get(RoomEntityDao.class).clone();
        roomEntityDaoConfig.initIdentityScope(type);

        memberEntityDaoConfig = daoConfigMap.get(MemberEntityDao.class).clone();
        memberEntityDaoConfig.initIdentityScope(type);

        friendEntityDao = new FriendEntityDao(friendEntityDaoConfig, this);
        roomsMemberEntityDao = new RoomsMemberEntityDao(roomsMemberEntityDaoConfig, this);
        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        profileEntityDao = new ProfileEntityDao(profileEntityDaoConfig, this);
        roomEntityDao = new RoomEntityDao(roomEntityDaoConfig, this);
        memberEntityDao = new MemberEntityDao(memberEntityDaoConfig, this);

        registerDao(FriendEntity.class, friendEntityDao);
        registerDao(RoomsMemberEntity.class, roomsMemberEntityDao);
        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(ProfileEntity.class, profileEntityDao);
        registerDao(RoomEntity.class, roomEntityDao);
        registerDao(MemberEntity.class, memberEntityDao);
    }
    
    public void clear() {
        friendEntityDaoConfig.getIdentityScope().clear();
        roomsMemberEntityDaoConfig.getIdentityScope().clear();
        messageEntityDaoConfig.getIdentityScope().clear();
        profileEntityDaoConfig.getIdentityScope().clear();
        roomEntityDaoConfig.getIdentityScope().clear();
        memberEntityDaoConfig.getIdentityScope().clear();
    }

    public FriendEntityDao getFriendEntityDao() {
        return friendEntityDao;
    }

    public RoomsMemberEntityDao getRoomsMemberEntityDao() {
        return roomsMemberEntityDao;
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public ProfileEntityDao getProfileEntityDao() {
        return profileEntityDao;
    }

    public RoomEntityDao getRoomEntityDao() {
        return roomEntityDao;
    }

    public MemberEntityDao getMemberEntityDao() {
        return memberEntityDao;
    }

}
