package org.ertebat.pdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FRIEND_ENTITY.
 */
public class FriendEntity {

    private Long id;
    private String friendId;
    private String userName;
    private String state;

    public FriendEntity() {
    }

    public FriendEntity(Long id) {
        this.id = id;
    }

    public FriendEntity(Long id, String friendId, String userName, String state) {
        this.id = id;
        this.friendId = friendId;
        this.userName = userName;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFriendId() {
        return friendId;
    }

    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

}
