package org.ertebat.pdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROFILE_ENTITY.
 */
public class ProfileEntity {

    private Long id;
    private String userName;
    private String token;
    private String uuid;
    private String pictureURL;
    private String firstName;
    private String lastName;
    private String email;

    public ProfileEntity() {
    }

    public ProfileEntity(Long id) {
        this.id = id;
    }

    public ProfileEntity(Long id, String userName, String token, String uuid, String pictureURL, String firstName, String lastName, String email) {
        this.id = id;
        this.userName = userName;
        this.token = token;
        this.uuid = uuid;
        this.pictureURL = pictureURL;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getPictureURL() {
        return pictureURL;
    }

    public void setPictureURL(String pictureURL) {
        this.pictureURL = pictureURL;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
