package org.ertebat.pdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ROOM_ENTITY.
 */
public class RoomEntity {

    private Long id;
    private String name;
    private String desc;
    private String logo;
    private String type;
    private String roomId;

    public RoomEntity() {
    }

    public RoomEntity(Long id) {
        this.id = id;
    }

    public RoomEntity(Long id, String name, String desc, String logo, String type, String roomId) {
        this.id = id;
        this.name = name;
        this.desc = desc;
        this.logo = logo;
        this.type = type;
        this.roomId = roomId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRoomId() {
        return roomId;
    }

    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

}
